### ISSUE TITLE
Error on docker-compose up

### ISSUE THREAD

**Issue by thatnerdjosh** [demyxco/elgg#1]
```
elgg       | SQLSTATE[42S02]: Base table or view not found: 1146 Table 'demyx_db.elgg_config' doesn't exist at /var/www/html/vendor/elgg/elgg/engine/classes/Elgg/Database.p
elgg       | 2020/01/01 22:56:17 [error] 279#279: *1 FastCGI sent in stderr: "ag('attributes')
elgg       | #8 /var/www/html/vendor/symfony/http-foundation/Session/Session.php(280): Symfony\Component\HttpFoundation\Session\Session->getBag('attributes')
elgg       | #9 /var/www/html/vendor/symfony/http-foundation/Session/Session.php(73): Symfony\Component\HttpFoundation\Session\Session->getAttributeBag()
elgg       | #10 /var/www/html/vendor/elgg/elgg/engine/classes/ElggSession.php(165): Symfony\Component\HttpFoundation\Session\Session->get('_elgg_msgs', Array)
elgg       | #11 /var/www/html/vendor/elgg/elgg/engine/classes/Elgg/SystemMessagesService.php(122): ElggSession->get('_elgg_msgs', Array)
elgg       | #12 /var/www/html/vendor/elgg/elgg/engine/classes/Elgg/SystemMessagesService.php(74): Elgg\SystemMessagesService->loadRegisters()
elgg       | #13 /var/www/html/vendor/elgg/elgg/engine/lib/views.php(377): Elgg\SystemMessagesService->count()
elgg       | #14 /var/www/html/vendor/elgg/elgg/engine/classes/Elgg/Application/ExceptionHandler.php(121): elgg_view_page('Fatal Error.', '')
elgg       | #15 [internal function]: Elgg\Application\ExceptionHandler->__invoke(Object(DatabaseException))
elgg       | #16 {main}
elgg       |  {"exception":"[object] (DatabaseException(code: 0): An exception occurred while executing 'SELECT *
elgg       | \t\t\tFROM elgg_users_sessions
elgg       | \t\t\tWHERE session = ?' with params [\"4n9afrtgmmiop2j33qbtg2n1mg\"]:
elgg       |
elgg       | SQLSTATE[42S02]: Base table or view not found: 1146 Table 'demyx_db.elgg_users_sessions' doesn't exist at /var/www/html/vendor/elgg/elgg/engine/classes/Elgg/Database.php:448)","sql":"SELECT *
elgg       | \t\t\tFROM elgg_users_sessions
elgg       | \t\t\tWHERE session = :session_id","params":{":session_id":"4n9afrtgmmiop2j33qbtg2n1mg"}} {"backtrace":[],"process_id":289,"memory_peak_usage":"4 MB","memory_usage":"4 MB","url":"/","ip":"172.22.0.3","http_method":"GET","server":"domain.tld","referrer":null}" while reading response header from upstream, client: 172.22.0.3, server: domain.tld, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "domain.tld"
elgg       | 127.0.0.1 -  01/Jan/2020:22:56:16 -0800 "GET /index.php" 500

```

**Comment by demyxco** [comment]
Hi, I've updated the paths to both Elgg and MariaDB images. Please have a look at the updated [docker-compose.yml](https://github.com/demyxco/elgg/blob/master/docker-compose.yml).

**Comment by demyxco** [comment]
Closing this as the problem has been resolved.
